import "server-only";

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb } from "pdf-lib";
import PptxGenJS from "pptxgenjs";
import * as XLSX from "xlsx";
import { safeFileName } from "@/lib/storage";
import { normalizeOutputDefinitions, type AgentArtifactFormat } from "./artifact-contract";

export interface GeneratedAgentArtifact {
  filename: string;
  format: AgentArtifactFormat;
  type: "markdown" | "text" | "json" | "file";
  mimeType: string;
  bytes: Buffer;
  contentText: string | null;
}

const MAX_ARTIFACT_BYTES = 20 * 1024 * 1024;

function documentBlocks(markdown: string) {
  return markdown.replace(/\r\n/g, "\n").split("\n").map((raw) => {
    const line = raw.trim();
    const heading = /^(#{1,3})\s+(.+)$/.exec(line);
    const bullet = /^[-*]\s+(.+)$/.exec(line);
    const numbered = /^\d+[.)]\s+(.+)$/.exec(line);
    if (heading) return { kind: "heading" as const, level: heading[1].length, text: heading[2] };
    if (bullet || numbered) return { kind: "bullet" as const, level: 1, text: (bullet ?? numbered)![1] };
    return { kind: "paragraph" as const, level: 0, text: line.replace(/[*_`]/g, "") };
  });
}

function artifactStem(taskTitle: string, definitionName: string) {
  return safeFileName(`${taskTitle}-${definitionName}`.normalize("NFKC").replace(/\s+/g, "-")).replace(/\.[^.]+$/, "").slice(0, 180) || "agent-output";
}

async function makeDocx(title: string, markdown: string) {
  const children = [
    new Paragraph({ text: title, heading: HeadingLevel.TITLE, alignment: AlignmentType.LEFT }),
    new Paragraph({ children: [new TextRun({ text: "Generated by Woli Agent Work", color: "667085", italics: true })], spacing: { after: 240 } }),
    ...documentBlocks(markdown).map((block) => {
      if (block.kind === "heading") {
        const heading = block.level === 1 ? HeadingLevel.HEADING_1 : block.level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3;
        return new Paragraph({ text: block.text, heading, spacing: { before: 180, after: 90 } });
      }
      if (block.kind === "bullet") return new Paragraph({ text: block.text, bullet: { level: 0 }, spacing: { after: 70 } });
      return new Paragraph({ text: block.text || " ", spacing: { after: 90, line: 300 } });
    }),
  ];
  const doc = new Document({ sections: [{ properties: {}, children }] });
  return Buffer.from(await Packer.toBuffer(doc));
}

function makeXlsx(title: string, markdown: string) {
  const blocks = documentBlocks(markdown).filter((block) => block.text);
  const workbook = XLSX.utils.book_new();
  const summary = XLSX.utils.aoa_to_sheet([
    ["Woli Agent Work output", title],
    ["Generated at", new Date().toISOString()],
    ["Content rows", { f: "COUNTA(Content!B:B)-1" }],
    ["Heading rows", { f: "COUNTIF(Content!A:A,\"Heading*\")" }],
  ]);
  summary["!cols"] = [{ wch: 24 }, { wch: 72 }];
  const rows = [["Type", "Content"], ...blocks.map((block) => [block.kind === "heading" ? `Heading ${block.level}` : block.kind === "bullet" ? "List item" : "Paragraph", block.text])];
  const content = XLSX.utils.aoa_to_sheet(rows);
  content["!cols"] = [{ wch: 18 }, { wch: 110 }];
  content["!autofilter"] = { ref: `A1:B${Math.max(1, rows.length)}` };
  XLSX.utils.book_append_sheet(workbook, summary, "Summary");
  XLSX.utils.book_append_sheet(workbook, content, "Content");
  return Buffer.from(XLSX.write(workbook, { type: "buffer", bookType: "xlsx", compression: true }));
}

function chunkText(text: string, max = 900) {
  const chunks: string[] = [];
  let remaining = text.trim();
  while (remaining) {
    if (remaining.length <= max) {
      chunks.push(remaining);
      break;
    }
    const cut = Math.max(200, remaining.lastIndexOf("\n", max), remaining.lastIndexOf(" ", max));
    chunks.push(remaining.slice(0, cut).trim());
    remaining = remaining.slice(cut).trim();
  }
  return chunks;
}

async function makePptx(title: string, markdown: string) {
  const presentation = new PptxGenJS();
  presentation.layout = "LAYOUT_WIDE";
  presentation.author = "Woli Agent Work";
  presentation.subject = "Agent-generated artifact";
  presentation.title = title;
  presentation.company = "Woli";
  presentation.theme = { headFontFace: "Aptos Display", bodyFontFace: "Aptos" };

  const cover = presentation.addSlide();
  cover.background = { color: "F7F8FA" };
  cover.addShape(presentation.ShapeType.rect, { x: 0, y: 0, w: 0.2, h: 7.5, fill: { color: "4F46E5" }, line: { color: "4F46E5" } });
  cover.addText(title, { x: 0.8, y: 2.35, w: 11.7, h: 1.2, fontFace: "Aptos Display", fontSize: 30, bold: true, color: "111827", margin: 0 });
  cover.addText("Generated by Woli Agent Work", { x: 0.82, y: 3.75, w: 7, h: 0.4, fontSize: 14, color: "667085", margin: 0 });

  const chunks = chunkText(documentBlocks(markdown).map((block) => block.text).filter(Boolean).join("\n\n"));
  for (const [index, chunk] of chunks.entries()) {
    const slide = presentation.addSlide();
    slide.background = { color: "FFFFFF" };
    slide.addText(index === 0 ? title : `${title} (${index + 1})`, { x: 0.65, y: 0.45, w: 12, h: 0.55, fontSize: 22, bold: true, color: "1F2937", margin: 0 });
    slide.addShape(presentation.ShapeType.line, { x: 0.65, y: 1.15, w: 12, h: 0, line: { color: "E5E7EB", width: 1 } });
    slide.addText(chunk, { x: 0.75, y: 1.45, w: 11.8, h: 5.35, fontSize: 16, color: "374151", breakLine: false, valign: "top", margin: 0.08, paraSpaceAfter: 9, fit: "shrink" });
    slide.addText(`${index + 1} / ${chunks.length}`, { x: 11.5, y: 7.05, w: 1.1, h: 0.2, fontSize: 9, color: "9CA3AF", align: "right", margin: 0 });
  }
  const result = await presentation.write({ outputType: "nodebuffer", compression: true });
  return Buffer.from(result as Uint8Array);
}

function wrapPdfLine(text: string, font: { widthOfTextAtSize(value: string, size: number): number }, size: number, maxWidth: number) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) line = candidate;
    else {
      if (line) lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

async function makePdf(title: string, markdown: string) {
  const pdf = await PDFDocument.create();
  pdf.registerFontkit(fontkit);
  const fontPath = join(process.cwd(), "node_modules", "@fontsource", "noto-sans", "files", "noto-sans-vietnamese-400-normal.woff");
  const fontBytes = await readFile(fontPath);
  const font = await pdf.embedFont(fontBytes, { subset: true });
  const pageSize: [number, number] = [595.28, 841.89];
  const margin = 52;
  let page = pdf.addPage(pageSize);
  let y = pageSize[1] - margin;
  const addPage = () => { page = pdf.addPage(pageSize); y = pageSize[1] - margin; };
  const drawLine = (line: string, size: number, color = rgb(0.17, 0.2, 0.27), gap = 1.4) => {
    if (y < margin + size * gap) addPage();
    page.drawText(line, { x: margin, y, size, font, color });
    y -= size * gap;
  };
  for (const line of wrapPdfLine(title, font, 20, pageSize[0] - margin * 2)) drawLine(line, 20, rgb(0.08, 0.11, 0.18), 1.35);
  y -= 8;
  drawLine("Woli Agent Work", 9, rgb(0.42, 0.46, 0.53), 2);
  for (const block of documentBlocks(markdown)) {
    if (!block.text) { y -= 5; continue; }
    const size = block.kind === "heading" ? (block.level === 1 ? 16 : block.level === 2 ? 14 : 12) : 10.5;
    const prefix = block.kind === "bullet" ? "• " : "";
    if (block.kind === "heading") y -= 6;
    for (const line of wrapPdfLine(`${prefix}${block.text}`, font, size, pageSize[0] - margin * 2)) drawLine(line, size, block.kind === "heading" ? rgb(0.1, 0.13, 0.2) : rgb(0.22, 0.25, 0.31));
    y -= block.kind === "heading" ? 3 : 2;
  }
  return Buffer.from(await pdf.save());
}

export async function generateAgentArtifacts(args: { taskTitle: string; markdown: string; definitions: unknown }): Promise<GeneratedAgentArtifact[]> {
  const definitions = normalizeOutputDefinitions(args.definitions);
  const artifacts: GeneratedAgentArtifact[] = [];
  for (const definition of definitions) {
    const stem = artifactStem(args.taskTitle, definition.name);
    let artifact: GeneratedAgentArtifact;
    if (definition.format === "markdown") {
      artifact = { filename: `${stem}.md`, format: definition.format, type: "markdown", mimeType: "text/markdown; charset=utf-8", bytes: Buffer.from(args.markdown, "utf8"), contentText: args.markdown };
    } else if (definition.format === "text") {
      const text = documentBlocks(args.markdown).map((block) => block.text).join("\n");
      artifact = { filename: `${stem}.txt`, format: definition.format, type: "text", mimeType: "text/plain; charset=utf-8", bytes: Buffer.from(text, "utf8"), contentText: text };
    } else if (definition.format === "json") {
      const text = JSON.stringify({ title: args.taskTitle, generatedAt: new Date().toISOString(), content: args.markdown }, null, 2);
      artifact = { filename: `${stem}.json`, format: definition.format, type: "json", mimeType: "application/json; charset=utf-8", bytes: Buffer.from(text, "utf8"), contentText: text };
    } else if (definition.format === "docx") {
      artifact = { filename: `${stem}.docx`, format: definition.format, type: "file", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", bytes: await makeDocx(definition.name, args.markdown), contentText: null };
    } else if (definition.format === "xlsx") {
      artifact = { filename: `${stem}.xlsx`, format: definition.format, type: "file", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", bytes: makeXlsx(definition.name, args.markdown), contentText: null };
    } else if (definition.format === "pptx") {
      artifact = { filename: `${stem}.pptx`, format: definition.format, type: "file", mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", bytes: await makePptx(definition.name, args.markdown), contentText: null };
    } else {
      artifact = { filename: `${stem}.pdf`, format: definition.format, type: "file", mimeType: "application/pdf", bytes: await makePdf(definition.name, args.markdown), contentText: null };
    }
    if (!artifact.bytes.length || artifact.bytes.length > MAX_ARTIFACT_BYTES) throw new Error(`Generated artifact is outside the allowed size: ${artifact.filename}`);
    artifacts.push(artifact);
  }
  return artifacts;
}
