// Writes shell/config.js from the environment before `tauri dev|build`.
// BASEWORK_SERVER_URL is the production web app origin. It is not a secret:
// the desktop app is just a window onto the same web app and API.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const DEFAULT_URL = "https://hr-task-managent-cl-o1sz.vercel.app";
const raw = (process.env.BASEWORK_SERVER_URL || DEFAULT_URL).trim().replace(/\/+$/, "");
const url = new URL(raw);
const isLocal = url.hostname === "localhost" || url.hostname === "127.0.0.1";
if (url.protocol !== "https:" && !isLocal) {
  console.error(`BASEWORK_SERVER_URL must use https:// (got ${raw})`);
  process.exit(1);
}
const out = fileURLToPath(new URL("../shell/config.js", import.meta.url));
writeFileSync(out, `// Generated by scripts/prepare-shell.mjs - do not edit.\nwindow.BASEWORK_CONFIG = ${JSON.stringify({ serverUrl: url.origin })};\n`);
console.log(`[desktop] server URL: ${url.origin}`);
