use std::fs;

// The server origin is read from ../shell/config.js (generated by
// scripts/prepare-shell.mjs from BASEWORK_SERVER_URL) so the bootstrap page and
// the native navigation allow-list can never point at different servers.
fn main() {
    println!("cargo:rerun-if-changed=../shell/config.js");
    let config = fs::read_to_string("../shell/config.js")
        .expect("shell/config.js missing - run `npm run prepare-shell` in desktop/ first");
    let key = "\"serverUrl\":\"";
    let start = config.find(key).expect("serverUrl not found in shell/config.js") + key.len();
    let end = start + config[start..].find('"').expect("unterminated serverUrl");
    let url = &config[start..end];
    assert!(
        url.starts_with("https://") || url.starts_with("http://localhost") || url.starts_with("http://127.0.0.1"),
        "server URL must be https (got {url})"
    );
    println!("cargo:rustc-env=BASEWORK_SERVER_URL={url}");
    tauri_build::build()
}
