"use client";
import { markdownToHtml } from "./markdown";

const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

/**
 * Export an AI report as PDF through the browser's print dialog ("Save as PDF").
 * Printing keeps Vietnamese text, tables and fonts exact without shipping a
 * PDF engine to the client.
 */
export function exportReportPdf(opts: { markdown: string; title: string; workspace: string; author: string; logoUrl?: string | null; locale: "vi" | "en" }) {
  const body = markdownToHtml(opts.markdown);
  const date = new Date().toLocaleString(opts.locale === "vi" ? "vi-VN" : "en-GB", { dateStyle: "long", timeStyle: "short" });
  const html = `<!doctype html><html lang="${opts.locale}"><head><meta charset="utf-8"><title>${esc(opts.title)}</title>
<style>
  @page { size: A4; margin: 18mm 16mm 20mm; }
  * { box-sizing: border-box; }
  body { font-family: "Segoe UI", system-ui, -apple-system, Roboto, Arial, sans-serif; color: #1f2937; font-size: 11pt; line-height: 1.55; margin: 0; }
  header { display: flex; align-items: center; gap: 10px; border-bottom: 2px solid #ea580c; padding-bottom: 10px; margin-bottom: 18px; }
  header img { width: 34px; height: 34px; border-radius: 8px; object-fit: cover; }
  header .ws { font-weight: 700; font-size: 12pt; }
  header .meta { margin-left: auto; text-align: right; font-size: 8.5pt; color: #6b7280; }
  h1 { font-size: 19pt; margin: 0 0 8px; color: #111827; }
  h2 { font-size: 14pt; margin: 18px 0 6px; color: #9a3412; border-bottom: 1px solid #fed7aa; padding-bottom: 3px; }
  h3 { font-size: 12pt; margin: 14px 0 4px; }
  p, li { orphans: 3; widows: 3; }
  ul, ol { padding-left: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 9.5pt; page-break-inside: auto; }
  tr { page-break-inside: avoid; }
  th, td { border: 1px solid #e5e7eb; padding: 5px 7px; text-align: left; vertical-align: top; }
  th { background: #fff7ed; }
  code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; }
  blockquote { border-left: 3px solid #fdba74; margin: 8px 0; padding-left: 10px; color: #4b5563; }
  footer { margin-top: 28px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; }
</style></head><body>
<header>${opts.logoUrl ? `<img src="${esc(opts.logoUrl)}" alt="">` : ""}<span class="ws">${esc(opts.workspace)}</span>
<span class="meta">${esc(opts.author)}<br>${esc(date)}</span></header>
<main>${body}</main>
<footer>${opts.locale === "vi" ? "Tạo bởi woli AI từ dữ liệu bạn được phép xem. Hãy kiểm tra lại các số liệu quan trọng." : "Generated by woli AI from the data you are allowed to see. Please double-check key figures."}</footer>
</body></html>`;
  const frame = document.createElement("iframe");
  frame.style.position = "fixed";
  frame.style.right = "0";
  frame.style.bottom = "0";
  frame.style.width = "0";
  frame.style.height = "0";
  frame.style.border = "0";
  frame.setAttribute("aria-hidden", "true");
  document.body.appendChild(frame);
  const doc = frame.contentDocument!;
  doc.open();
  doc.write(html);
  doc.close();
  const go = () => {
    frame.contentWindow!.focus();
    frame.contentWindow!.print();
    setTimeout(() => frame.remove(), 60_000);
  };
  // Wait for the logo (if any) so it appears in the PDF.
  const img = doc.querySelector("img");
  if (img && !img.complete) {
    img.addEventListener("load", go, { once: true });
    img.addEventListener("error", go, { once: true });
  } else setTimeout(go, 50);
}
